-- ============================================================
-- PROJECT 2 - TECHPOINT SOLUTIONS
-- PostgreSQL Database Construction
-- Database: Techpoint_Solutions
-- Schema: public
--
-- Creates the final approved 12-table relational model.
-- ============================================================

-- 01. CATEGORIES
CREATE TABLE public.categories (
    categoryid integer GENERATED BY DEFAULT AS IDENTITY,
    categoryname varchar(50) NOT NULL,
    description varchar(255),
    CONSTRAINT pk_categories PRIMARY KEY (categoryid),
    CONSTRAINT uq_categories_categoryname UNIQUE (categoryname)
);

-- 02. CUSTOMERS
CREATE TABLE public.customers (
    customerid integer GENERATED BY DEFAULT AS IDENTITY,
    customertype varchar(50) NOT NULL,
    customername varchar(100) NOT NULL,
    email varchar(100),
    phone varchar(25),
    registrationdate date,
    status varchar(20) NOT NULL,
    CONSTRAINT pk_customers PRIMARY KEY (customerid),
    CONSTRAINT chk_customers_customertype
        CHECK (customertype IN ('Individual', 'Business')),
    CONSTRAINT chk_customers_status
        CHECK (status IN ('Active', 'Inactive'))
);

-- 03. EMPLOYEES
CREATE TABLE public.employees (
    employeeid integer GENERATED BY DEFAULT AS IDENTITY,
    firstname varchar(50) NOT NULL,
    lastname varchar(50) NOT NULL,
    role varchar(50),
    email varchar(100),
    hiredate date,
    CONSTRAINT pk_employees PRIMARY KEY (employeeid)
);

-- 04. SUPPLIERS
CREATE TABLE public.suppliers (
    supplierid integer GENERATED BY DEFAULT AS IDENTITY,
    suppliername varchar(100) NOT NULL,
    contactname varchar(100) NOT NULL,
    email varchar(100),
    phone varchar(30),
    status varchar(20) NOT NULL DEFAULT 'Active',
    CONSTRAINT pk_suppliers PRIMARY KEY (supplierid),
    CONSTRAINT chk_suppliers_status
        CHECK (status IN ('Active', 'Inactive'))
);

-- 05. PRODUCTS
CREATE TABLE public.products (
    productid integer GENERATED BY DEFAULT AS IDENTITY,
    sku varchar(30) NOT NULL,
    productname varchar(100) NOT NULL,
    categoryid integer NOT NULL,
    sellingprice numeric(12,2) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'Active',
    CONSTRAINT pk_products PRIMARY KEY (productid),
    CONSTRAINT uq_products_sku UNIQUE (sku),
    CONSTRAINT chk_products_sellingprice CHECK (sellingprice >= 0),
    CONSTRAINT chk_products_status
        CHECK (status IN ('Active', 'Inactive')),
    CONSTRAINT fk_products_category
        FOREIGN KEY (categoryid)
        REFERENCES public.categories(categoryid)
);

-- 06. PRODUCTSUPPLIERS
CREATE TABLE public.productsuppliers (
    productid integer NOT NULL,
    supplierid integer NOT NULL,
    supplierproductcode varchar(50),
    unitcost numeric(12,2) NOT NULL,
    leadtimedays integer NOT NULL,
    isprimarysupplier boolean DEFAULT FALSE,
    CONSTRAINT pk_productsuppliers PRIMARY KEY (productid, supplierid),
    CONSTRAINT fk_productsuppliers_product
        FOREIGN KEY (productid)
        REFERENCES public.products(productid),
    CONSTRAINT fk_productsuppliers_supplier
        FOREIGN KEY (supplierid)
        REFERENCES public.suppliers(supplierid),
    CONSTRAINT chk_productsuppliers_unitcost CHECK (unitcost >= 0),
    CONSTRAINT chk_productsuppliers_leadtimedays CHECK (leadtimedays >= 0)
);

-- One primary supplier per product.
CREATE UNIQUE INDEX uq_productsuppliers_primary_supplier
ON public.productsuppliers (productid)
WHERE isprimarysupplier = TRUE;

-- 07. PURCHASES
CREATE TABLE public.purchases (
    purchaseid integer GENERATED BY DEFAULT AS IDENTITY,
    supplierid integer NOT NULL,
    purchasedate date NOT NULL,
    purchasestatus varchar(20) NOT NULL DEFAULT 'Pending',
    CONSTRAINT pk_purchases PRIMARY KEY (purchaseid),
    CONSTRAINT fk_purchases_supplier
        FOREIGN KEY (supplierid)
        REFERENCES public.suppliers(supplierid),
    CONSTRAINT chk_purchases_status
        CHECK (purchasestatus IN ('Pending', 'Received', 'Cancelled'))
);

CREATE INDEX ix_purchases_supplierid
ON public.purchases (supplierid);

CREATE INDEX ix_purchases_purchasedate
ON public.purchases (purchasedate);

-- 08. PURCHASEDETAILS
CREATE TABLE public.purchasedetails (
    purchasedetailid integer GENERATED BY DEFAULT AS IDENTITY,
    purchaseid integer NOT NULL,
    productid integer NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    unitcost numeric(12,2) NOT NULL,
    CONSTRAINT pk_purchasedetails PRIMARY KEY (purchasedetailid),
    CONSTRAINT fk_purchasedetails_purchase
        FOREIGN KEY (purchaseid)
        REFERENCES public.purchases(purchaseid),
    CONSTRAINT fk_purchasedetails_product
        FOREIGN KEY (productid)
        REFERENCES public.products(productid),
    CONSTRAINT chk_purchasedetails_quantity CHECK (quantity > 0),
    CONSTRAINT chk_purchasedetails_unitcost CHECK (unitcost >= 0)
);

CREATE INDEX ix_purchasedetails_purchaseid
ON public.purchasedetails (purchaseid);

CREATE INDEX ix_purchasedetails_productid
ON public.purchasedetails (productid);

-- 09. INVENTORY
CREATE TABLE public.inventory (
    inventoryid integer GENERATED BY DEFAULT AS IDENTITY,
    productid integer NOT NULL,
    quantityonhand integer NOT NULL DEFAULT 0,
    reorderlevel integer NOT NULL DEFAULT 0,
    lastupdated timestamp without time zone NOT NULL,
    CONSTRAINT pk_inventory PRIMARY KEY (inventoryid),
    CONSTRAINT uq_inventory_productid UNIQUE (productid),
    CONSTRAINT fk_inventory_product
        FOREIGN KEY (productid)
        REFERENCES public.products(productid),
    CONSTRAINT chk_inventory_quantityonhand
        CHECK (quantityonhand >= 0),
    CONSTRAINT chk_inventory_reorderlevel
        CHECK (reorderlevel >= 0)
);

-- 10. SALES
CREATE TABLE public.sales (
    saleid integer GENERATED BY DEFAULT AS IDENTITY,
    customerid integer NOT NULL,
    employeeid integer NOT NULL,
    saledate timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paymentmethod varchar(30) NOT NULL DEFAULT 'Credit Card',
    salestatus varchar(20) NOT NULL DEFAULT 'Completed',
    CONSTRAINT pk_sales PRIMARY KEY (saleid),
    CONSTRAINT fk_sales_customer
        FOREIGN KEY (customerid)
        REFERENCES public.customers(customerid),
    CONSTRAINT fk_sales_employee
        FOREIGN KEY (employeeid)
        REFERENCES public.employees(employeeid),
    CONSTRAINT chk_sales_paymentmethod
        CHECK (
            paymentmethod IN
            ('Cash', 'Credit Card', 'Debit Card', 'Bank Transfer')
        ),
    CONSTRAINT chk_sales_status
        CHECK (salestatus IN ('Completed', 'Cancelled'))
);

-- 11. SALEDETAILS
CREATE TABLE public.saledetails (
    saledetailid integer GENERATED BY DEFAULT AS IDENTITY,
    saleid integer NOT NULL DEFAULT 0,
    productid integer NOT NULL DEFAULT 0,
    quantity integer NOT NULL DEFAULT 1,
    unitprice numeric(12,2) NOT NULL,
    CONSTRAINT pk_saledetails PRIMARY KEY (saledetailid),
    CONSTRAINT fk_saledetails_sale
        FOREIGN KEY (saleid)
        REFERENCES public.sales(saleid),
    CONSTRAINT fk_saledetails_product
        FOREIGN KEY (productid)
        REFERENCES public.products(productid),
    CONSTRAINT chk_saledetails_quantity CHECK (quantity > 0),
    CONSTRAINT chk_saledetails_unitprice CHECK (unitprice >= 0)
);

-- 12. INVENTORYMOVEMENTS
CREATE TABLE public.inventorymovements (
    inventorymovementid integer GENERATED BY DEFAULT AS IDENTITY,
    productid integer NOT NULL DEFAULT 0,
    movementdate timestamp without time zone NOT NULL,
    movementtype varchar(30) NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    purchasedetailid integer NULL DEFAULT 0,
    saledetailid integer NULL DEFAULT 0,
    notes varchar(255) NULL,
    CONSTRAINT pk_inventorymovements PRIMARY KEY (inventorymovementid),
    CONSTRAINT fk_inventorymovements_product
        FOREIGN KEY (productid)
        REFERENCES public.products(productid),
    CONSTRAINT fk_inventorymovements_purchasedetail
        FOREIGN KEY (purchasedetailid)
        REFERENCES public.purchasedetails(purchasedetailid),
    CONSTRAINT fk_inventorymovements_saledetail
        FOREIGN KEY (saledetailid)
        REFERENCES public.saledetails(saledetailid),
    CONSTRAINT chk_inventorymovements_type
        CHECK (
            movementtype IN (
                'Purchase Receipt',
                'Sale',
                'Inventory Increase',
                'Inventory Decrease',
                'Return'
            )
        ),
    CONSTRAINT chk_inventorymovements_quantity CHECK (quantity > 0)
);
